/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectosm;

import java.io.File;
import sm.sound.SMClipPlayer;
import sm.sound.SMRecorder;
import sm.sound.SMSoundRecorder;

/**
 * @author Daniel Guerra Ruiz
 * @version 16/6/2015
 * Clase Ventana InternaGrabador.
 * Es un grabador de audio, se le pasa el fichero destino al principio.
 */
public class VentanaInternaGrabador extends javax.swing.JInternalFrame {

    /**
     * Constructor sin parámetros
     */
    public VentanaInternaGrabador() {
       initComponents();
       super.closable=true;
       super.resizable=true;
       super.maximizable=true;
       super.iconable=true;
    }
    
    SMRecorder recorder;
    /**
     * Consructor con parámetros
     * Se le pasa un fichero en el cual se grabará el audio.
     * @param f File
     */
    
     public VentanaInternaGrabador(File f) {
        initComponents();
        recorder = new SMSoundRecorder(f);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        botonGrabar = new javax.swing.JToggleButton();
        botonStopGrabar = new javax.swing.JToggleButton();

        setClosable(true);
        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(237, 100));
        setPreferredSize(new java.awt.Dimension(237, 100));
        getContentPane().setLayout(new java.awt.FlowLayout());

        buttonGroup1.add(botonGrabar);
        botonGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectosm/iconosSonido/record24x24.png"))); // NOI18N
        botonGrabar.setText("Grabar");
        botonGrabar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                botonGrabarStateChanged(evt);
            }
        });
        botonGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGrabarActionPerformed(evt);
            }
        });
        getContentPane().add(botonGrabar);

        buttonGroup1.add(botonStopGrabar);
        botonStopGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectosm/iconosSonido/stopRecord24x24.png"))); // NOI18N
        botonStopGrabar.setText("Stop");
        botonStopGrabar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                botonStopGrabarStateChanged(evt);
            }
        });
        botonStopGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonStopGrabarActionPerformed(evt);
            }
        });
        getContentPane().add(botonStopGrabar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Accion: Grabar audio
     * @param evt 
     */
    private void botonGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGrabarActionPerformed
        // TODO add your handling code here:
        if(recorder!=null)
            recorder.record();
    }//GEN-LAST:event_botonGrabarActionPerformed
    
    /**
     * Accion: Parar grabacion
     * @param evt 
     */
    private void botonStopGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonStopGrabarActionPerformed
        // TODO add your handling code here:
        if(recorder!=null)
            recorder.stop();
    }//GEN-LAST:event_botonStopGrabarActionPerformed

    private void botonGrabarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_botonGrabarStateChanged

    }//GEN-LAST:event_botonGrabarStateChanged

    private void botonStopGrabarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_botonStopGrabarStateChanged
 
    }//GEN-LAST:event_botonStopGrabarStateChanged

                                     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botonGrabar;
    private javax.swing.JToggleButton botonStopGrabar;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables
}
