/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectosm;

import java.awt.Color;
import java.awt.Point;
import java.awt.geom.Point2D;
import sm.dgr.iu.Lienzo2DImagen;

/**
 * @author Daniel Guerra Ruiz
 * @version 16/6/2015
 * Clase VentanaInternaImagen
 * Es el lienzo donde se pintarán las figuras y las imagenes.
 */
public class VentanaInternaImagen extends javax.swing.JInternalFrame {

    /**
     * Constructor sin parámetros
     */
    VentanaInternaImagen(){
          initComponents();
       super.closable=true;
       super.resizable=true;
       super.maximizable=true;
       super.iconable=true;
    }
    
    /**
     * Metodo getLienzo
     * Devuelve el lienzo de tipo Lienzo2DImagen
     * @return lienzo 
     */
    Lienzo2DImagen getLienzo(){
          return lienzo;
    }

    /**
     * Metodo setLienzo
     * Asigna al lienzo una imagen de tipo Lienzo2DImagen
     * @param l 
     */
    
    void setLienzo(Lienzo2DImagen l){
          lienzo=l;
    }
      
     
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lienzo = new sm.dgr.iu.Lienzo2DImagen();

        javax.swing.GroupLayout lienzoLayout = new javax.swing.GroupLayout(lienzo);
        lienzo.setLayout(lienzoLayout);
        lienzoLayout.setHorizontalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );
        lienzoLayout.setVerticalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        getContentPane().add(lienzo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sm.dgr.iu.Lienzo2DImagen lienzo;
    // End of variables declaration//GEN-END:variables
}
