/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectosm;

/**
 *
 * @author dani
 */
public class VentanaInternaSizeImagen extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaInternaSizeImagen
     */
    public VentanaInternaSizeImagen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(410, 60));
        setMinimumSize(new java.awt.Dimension(410, 60));
        setPreferredSize(new java.awt.Dimension(410, 60));

        jLabel1.setText("Establece el tamaño de la imagen");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jLabel2.setText("Alto:");
        jPanel1.add(jLabel2);

        jTextField1.setMaximumSize(new java.awt.Dimension(20, 20));
        jTextField1.setMinimumSize(new java.awt.Dimension(20, 20));
        jTextField1.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel1.add(jTextField1);

        jLabel4.setText("px");
        jPanel1.add(jLabel4);

        jSeparator3.setMinimumSize(new java.awt.Dimension(100, 10));
        jSeparator3.setPreferredSize(new java.awt.Dimension(100, 10));
        jPanel1.add(jSeparator3);

        jLabel3.setText("Ancho:");
        jPanel1.add(jLabel3);

        jTextField2.setMaximumSize(new java.awt.Dimension(20, 20));
        jTextField2.setMinimumSize(new java.awt.Dimension(20, 20));
        jTextField2.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel1.add(jTextField2);

        jLabel5.setText("px");
        jPanel1.add(jLabel5);

        jButton1.setText("Enviar");
        jPanel1.add(jButton1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jInternalFrame1.setMaximumSize(new java.awt.Dimension(410, 60));
        jInternalFrame1.setMinimumSize(new java.awt.Dimension(410, 60));
        jInternalFrame1.setPreferredSize(new java.awt.Dimension(410, 60));

        jLabel6.setText("Establece el tamaño de la imagen");
        jInternalFrame1.getContentPane().add(jLabel6, java.awt.BorderLayout.PAGE_START);

        jLabel7.setText("Alto:");
        jPanel2.add(jLabel7);

        jTextField3.setMaximumSize(new java.awt.Dimension(20, 20));
        jTextField3.setMinimumSize(new java.awt.Dimension(20, 20));
        jTextField3.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel2.add(jTextField3);

        jLabel8.setText("px");
        jPanel2.add(jLabel8);

        jSeparator4.setMinimumSize(new java.awt.Dimension(100, 10));
        jSeparator4.setPreferredSize(new java.awt.Dimension(100, 10));
        jPanel2.add(jSeparator4);

        jLabel9.setText("Ancho:");
        jPanel2.add(jLabel9);

        jTextField4.setMaximumSize(new java.awt.Dimension(20, 20));
        jTextField4.setMinimumSize(new java.awt.Dimension(20, 20));
        jTextField4.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel2.add(jTextField4);

        jLabel10.setText("px");
        jPanel2.add(jLabel10);

        jButton2.setText("Enviar");
        jPanel2.add(jButton2);

        jInternalFrame1.getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jInternalFrame1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
